# Generated by Django 2.1.15 on 2020-10-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='department',
        ),
    ]
