# Generated by Django 2.1.15 on 2020-10-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201027_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='priorty',
            new_name='priority',
        ),
    ]
