# Generated by Django 2.1.15 on 2020-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201027_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
