# Generated by Django 2.1.15 on 2020-10-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_item_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdescription',
            name='title',
        ),
    ]
