# Generated by Django 2.1.15 on 2020-11-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_itemdescription_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdescription',
            name='category_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='products.CategoryDescription'),
        ),
        migrations.AlterField(
            model_name='itemdescription',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descriptions', to='products.Item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.Item'),
        ),
    ]
