# Generated by Django 2.1.15 on 2020-11-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_delete_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cms_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='eventdetail',
            old_name='cms_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='cms_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='maincarouselitem',
            old_name='cms_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mainitem',
            old_name='cms_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notices',
            old_name='cms_user',
            new_name='user',
        ),
    ]
