# Generated by Django 2.1.15 on 2020-11-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201107_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
