# Generated by Django 2.1.15 on 2020-11-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201107_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
