# Generated by Django 2.1.15 on 2020-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201103_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
