# Generated by Django 2.1.15 on 2020-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_notices_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.RemoveField(
            model_name='notices',
            name='department',
        ),
    ]
