# Generated by Django 2.1.15 on 2020-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201107_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincarouselitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='mainitem',
            name='department',
        ),
        migrations.AddField(
            model_name='maincarouselitem',
            name='url',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mainitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='maincarouselitem',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
