# Generated by Django 2.1.15 on 2020-11-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201108_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincarouselitem',
            name='item',
        ),
    ]
