# Generated by Django 2.1.15 on 2020-11-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201103_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyData',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='user',
        ),
        migrations.DeleteModel(
            name='Manual',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
