# Generated by Django 2.1.15 on 2020-11-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_maincarouselitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincarouselitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maincarouselitem',
            name='url',
            field=models.TextField(default=None, null=True),
        ),
    ]
