# Generated by Django 2.1.15 on 2020-11-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201109_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincarouselitem',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='services.Event'),
        ),
    ]
