# Generated by Django 2.1.15 on 2020-11-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20201109_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
