# Generated by Django 2.1.15 on 2020-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20201111_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/%Y%m%d_%H%M%S_'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notices',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
